#!/bin/ruby
app_identifier "cz.ajty.WICS-CLIENT" # The bundle identifier of your app
apple_id "info@ajty.cz" # Your Apple email address

team_id "CDMJRT8WJB" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
