#!/bin/ruby
# Uncomment the lines below you want to change by removing the # in the beginning

reinstall_app = true
erase_simulator = true

# A list of devices you want to take the screenshots from
devices([
  "iPhone X",
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone SE",
  "iPad Air 2"
])

languages(["en-US"])

# The name of the scheme which contains the UI Tests
scheme "LunchGuy"

# Where should the resulting screenshots be stored?
# output_directory "./screenshots"

# clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# Arguments to pass to the app on launch. See https://github.com/fastlane/fastlane/tree/master/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help
